name: Compile LaTeX and Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: 'latest'

      - name: Compile LaTeX
        run: pdflatex main.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf